### ISSUE TITLE
[4.1] Mario Party gameboard misaligned

### ISSUE THREAD

**Issue by Eloo** [recalbox/recalbox-os#1106]
### What happened
If playing Mario Party 3 on N64 the gameboard is misaligned so the fields and the characters are not visible.

### What should have happened
The gameboard should be aligned correctly and the characters shoudl be visible

### Enumerate your devices
RPI3
RecalBox 4.1 alpha

### How to reproduce the bug
Start a game in Mario Party 3 with the default emulator settings

### My question
Is there any workaround or fix to get Mario Party 3 running properly? Is there a special configuration for this game?

Thanks and best regards
Eloo

**Comment by substring** [comment]
4.1 ? Do you mean it's a regression bug ?

**Comment by paradadf** [comment]
If I remember right, gliden64 corrected these not so long ago. It should be happening on 4.0 as well.

**Comment by Eloo** [comment]
@paradadf Okay, will test latest 4.0 build in time

**Comment by nicobevilacqua** [comment]
Same issue here, there are other games with hidden menus or missing sprites like pokemon stadium, mortal kombat 4, etc.

**Comment by paradadf** [comment]
These are all plugin (and/or RPI power) related. I know the hidden menus on Pokemon Stadium got fixed recently. The video pluings just need to be updated.

**Comment by rockaddicted** [comment]
Video plugin / core will be updated in recalbox 4.1, not before.
And even if a fix has been pushed upstream, it is not guaranteed that will work on rpi...
RPI is using an old and slow GLES2.0 GPU. So we can't accomplish miracles on N64 emulation.

**Comment by Eloo** [comment]
It seems that Mario Party 1 works with 4.1 build 63 but MP2 and MP3 are still misaligned

**Comment by paradadf** [comment]
The core/plugin hasn't been updated yet, so there are still no difference between 4.0 and 4.1 yet. IMO this issue should be closed as there is already one opened about this update.

**Comment by Eloo** [comment]
Okay, can you link the issue?

**Comment by paradadf** [comment]
https://github.com/recalbox/recalbox-os/issues/875

**Comment by Eloo** [comment]
Okay, so I will close this issue.
